spring:
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  datasource:
    url: "jdbc:h2:file:${user.dir}/data/studentdb"
    driver-class-name: org.h2.Driver
    username: sa
    password: